var OTAErrors = [
  'CYRET_SUCCESS',
  'CYRET_ERR_FILE',
  'CYRET_ERR_EOF',
  'CYRET_ERR_LENGTH',
  'CYRET_ERR_DATA',
  'CYRET_ERR_CMD',
  'CYRET_ERR_DEVICE',
  'CYRET_ERR_VERSION',
  'CYRET_ERR_CHECKSUM',
  'CYRET_ERR_ARRAY',
  'CYRET_BTLDR',
  'CYRET_ERR_APP',
  'CYRET_ERR_ACTIVE',
  'CYRET_ERR_UNK',
  'CYRET_ERR_ROW',
  'CYRET_ABORT'
]

module.exports = OTAErrors
